# Generated by Django 3.0.5 on 2020-04-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('increments', models.PositiveIntegerField(help_text='How many often should this medicine be administered?')),
                ('quantity', models.PositiveIntegerField(help_text='What quantity to be administered?')),
                ('start_date', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Meds',
                'verbose_name_plural': 'Meds',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.Meds')),
            ],
        ),
    ]
