# Generated by Django 3.0.5 on 2020-04-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
