# Generated by Django 3.0.5 on 2020-05-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200427_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meds',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='start_time',
        ),
    ]
