# Generated by Django 3.0.5 on 2020-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200511_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='unit',
            field=models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('MONTH', 'Month')], default='misc', max_length=30),
        ),
    ]
