# Generated by Django 3.0.5 on 2020-05-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meds_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='unit',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Month', 'Month')], default='misc', max_length=30),
        ),
    ]
