# Generated by Django 3.0.6 on 2020-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200511_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
