# Generated by Django 3.0.5 on 2020-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200511_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
