# Generated by Django 3.0.6 on 2020-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200512_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
