# Generated by Django 3.0.6 on 2020-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200512_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='start_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
