# Generated by Django 3.0.5 on 2020-05-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200512_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
