# Generated by Django 3.0.5 on 2020-05-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200512_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meds',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='start_time',
        ),
    ]
