# Generated by Django 3.0.5 on 2020-05-12 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200512_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meds',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
