# Generated by Django 3.0.6 on 2020-05-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('increments', models.PositiveIntegerField(help_text='How many often should this medicine be administered?')),
                ('quantity', models.PositiveIntegerField(help_text='What quantity to be administered?')),
                ('unit', models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Month', 'Month')], default='misc', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Meds',
                'verbose_name_plural': 'Meds',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='medtrax.Meds')),
            ],
        ),
    ]
