# Generated by Django 3.0.6 on 2020-06-18 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medtrax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_dose', models.DateTimeField(default=datetime.date.today)),
                ('comments', models.TextField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds_log', to='medtrax.Meds')),
            ],
            options={
                'ordering': ['-latest_dose'],
            },
        ),
    ]
