# Generated by Django 3.0.7 on 2020-06-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtrax', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.RemoveField(
            model_name='log',
            name='latest_dose',
        ),
    ]
